### ISSUE TITLE
Copy and Paste in Terminal

### ISSUE THREAD

**Issue by askovi** [hoobs-org/helm#3]
ctrl v doesn't paste in the win app terminal and there is no right click.

**Comment by mkellsy** [comment]
Copy and paste support has been added to version 1.2.3.

Since `ctrl+c` is the kill keystroke in the terminal, it can't be used. I did what Microsoft did. Right clicking will copy any selected text.

To paste, you can use `ctrl+v`. I can not paste on right click because the browser prevents it. Implicit access to the clipboard is a HUGE security issue. So I am not going to try to circumvent it, `ctrl+v` is a explicit "paste".

To update HelM, run this command, in HelM :)
```
sudo apt update && sudo apt install -y helm && sudo shutdown -r now
```
